config/routes.rb
Kvar::Application.routes.draw do

  scope :api, defaults: {format: :json} do
    resources :news_bites do
      get :create_image
    end
  end

  get '/', to: 'application#root'
  get 'about', to: 'application#root'

  get 'random', to: 'application#random'

  get '/:id', to: 'news_bites#show', as: 'nb'
  get '/:news_bite/:edit_key', to: 'application#root', as: 'news_bite_edit'


end

app/models/news_bite.rb
class NewsBite < ActiveRecord::Base

  acts_as_url :top_text#, sync_url: true

  scope :random, -> { order('random()').first }

  after_create :generate_edit_key

  def to_param
    url
  end

  def generate_edit_key
    self.update!(:edit_key => SecureRandom.urlsafe_base64(22))
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale

  def random
    redirect_to "/#{NewsBite.random.url}"
  end


  private
  def set_locale
    remote_ip = request.remote_ip
    #remote_ip = '81.218.176.116' - israel ip

    if params[:language]
      if ['he', 'en'].include? params[:language].downcase
        @language = params[:language].downcase
      else
        @language = 'en'
      end
      session[:language] = @language
    elsif session[:language]
      @language = session[:language]
    else
      geo_info = geoip.country(remote_ip)
      if geo_info != nil
        @language = geo_info[:country_code2] == 'IL' ? 'he' : 'en'
      else
        @language = {}
      end

      if remote_ip == "127.0.0.1" #todo: check for other local addresses or set default value
        @language = 'he'
      end
    end


  end

  def geoip
    @@geoip ||= GeoIP.new("#{Rails.root}/db/GeoIP.dat")
  end

end

app/controllers/news_bites_controller.rb
class NewsBitesController < ApplicationController

  before_action :set_news_bite, only: [:show, :update, :destroy]
  before_action :facebook_scraper, only: [:show]

  respond_to :json
  respond_to :html, only: [:show]

  def index
    @news_bites = NewsBite.all
    @news_bites.to_json

    respond_with @news_bites
  end


  def show
    respond_with @news_bite, scope: {:can_edit => can_edit?} do |format|
      format.html { render }
      format.jpg {
        send_data create_news_bite_image, type: 'image/jpeg', disposition: :inline
      }
    end
  end

  def create
    @news_bite = NewsBite.create(news_bite_params)
    session[:edit_key] = @news_bite.edit_key
    respond_with @news_bite
  end

  def create_image
    @news_bite = NewsBite.find_by(:url => params[:news_bite_id])
    @news_bite.update(:image_url => upload_news_bite_image)
    render :json => { :success => 'success'}
  end

  # PATCH/PUT /sites/1
  def update
    @news_bite.update(news_bite_params) if can_edit?
    render json: @news_bite
  end

  # DELETE /sites/1
  def destroy
    @news_bite.destroy
    respond_with @news_bite
  end

  private

    def can_edit?
      session[:edit_key] == @news_bite.edit_key
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_news_bite
      @news_bite = NewsBite.where(url: params.require(:id)).first
    end

    def news_bite_params
      params.require(:news_bite).permit(:top_text, :center_text)
    end

    def create_news_bite_image
      html = render_to_string('news_bites/facebook_image', layout: false, formats: 'html')
      kit = IMGKit.new(html, quality: 100, width: 1200, height: 627)
      kit.to_img(:jpg)
    end

    def upload_news_bite_image
      s3 = AWS::S3.new
      bucket = s3.buckets['newsyeti']
      obj = bucket.objects.create("#{@news_bite.url}.jpg", '???')
      obj.write(create_news_bite_image)
      obj.public_url.to_s
    rescue Exception => exception
      Rails.logger.warn "News Bite #{@news_bite.url} failed to upload image to AWS"
    end

    def facebook_scraper
      if request.user_agent.include? 'facebookexternalhit'
        render template: 'news_bites/facebook', layout: nil
      elsif request.format.html?
        render template: 'application/root'
      end
    end

end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <% if @news_bite.present? %>
  	<%= render 'news_bites/metas' %>
  <% else %>
  	<title>News Yeti</title>
  	<meta name="description" content="News Yeti is a site that lets you quickly and easily create news bites, short and to the point mini stories that you can share with people across the internet.">
  <% end %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <script>
    var language = <%= raw @language.to_json %>;
  </script>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/external_shares' %>
<%= yield %>
</body>
</html>

app/views/news_bites/_metas.html.erb
  <title><%= @news_bite.top_text %> - News Yeti</title>
  <meta name="description" content="News Yeti is a site that lets you quickly and easily create news bites, short and to the point mini stories that you can share with people across the internet.">
  <meta property="og:title" content="<%= @news_bite.top_text %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= nb_url(@news_bite) %>" />
  <meta property="og:image" content="<%= @news_bite.image_url %>" />

  <meta property="og:description" content="News Yeti is a site that lets you quickly and easily create news bites, short and to the point mini stories that you can share with people across the internet." />
  <meta property="og:site_name" content="News Yeti" />

app/views/news_bites/facebook.html.erb
<html>
<head>
 <%= render 'news_bites/metas' %>
</head>
<body>
	.
</body>
</html>

app/views/news_bites/facebook_image.html.erb
<html>
<head>
  <meta http-equiv='content-type' content='text/html;charset=utf-8'>
  <style>
    body {
      margin: 0;
      width: 1200px !important;
      background-image: url('<%="#{Rails.root}/app/assets/images/news-yeti-small.png" %>');
      background-repeat: no-repeat;
      background-position: 1000px 125px;
    }
    h1 {
      font-size: 75px;
      line-height: 86px;
      margin-left: 10px;
      width: 1000px;
      max-height: 627px;
      display: -webkit-box;
      position: relative;
      top: -50px;
      direction: ltr;
    }
  </style>
</head>
<body>
  <h1 id="title"><span><%=@news_bite.top_text%></span></h1>
  <script type="text/javascript">
    var titleElement = document.getElementById('title');
    if (/[א-ת]/.test(titleElement.innerHTML)) {
      titleElement.style.direction = 'rtl';
    }
  </script>

</body>
</html>